/* eslint-disable */
// GENERATED by scripts/gen-web-glue.mjs from @quantus-network/wasm@0.3.1 (pkg/quantus_wasm.js).
// Do not edit by hand.

/**
 * @param {Response | Promise<Response> | BufferSource} source the quantus_wasm_bg.wasm binary
 */
export async function loadQuantusWasm(source) {
  const exports = {};
  let wasm;
  /* @ts-self-types="./quantus_wasm.d.ts" */

  /**
   * Account material derived from a seed. Byte fields surface as `Uint8Array`.
   */
  class Account {
    static __wrap(ptr) {
      const obj = Object.create(Account.prototype);
      obj.__wbg_ptr = ptr;
      AccountFinalization.register(obj, obj.__wbg_ptr, obj);
      return obj;
    }
    __destroy_into_raw() {
      const ptr = this.__wbg_ptr;
      this.__wbg_ptr = 0;
      AccountFinalization.unregister(this);
      return ptr;
    }
    free() {
      const ptr = this.__destroy_into_raw();
      wasm.__wbg_account_free(ptr, 0);
    }
    /**
     * 32-byte Poseidon `AccountId32`.
     * @returns {Uint8Array}
     */
    get accountId() {
      const ret = wasm.account_accountId(this.__wbg_ptr);
      var v1 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
      wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
      return v1;
    }
    /**
     * SS58 address encoded with the Quantus prefix (189).
     * @returns {string}
     */
    get address() {
      let deferred1_0;
      let deferred1_1;
      try {
        const ret = wasm.account_address(this.__wbg_ptr);
        deferred1_0 = ret[0];
        deferred1_1 = ret[1];
        return getStringFromWasm0(ret[0], ret[1]);
      } finally {
        wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
      }
    }
    /**
     * ML-DSA-87 public key (2592 bytes).
     * @returns {Uint8Array}
     */
    get publicKey() {
      const ret = wasm.account_publicKey(this.__wbg_ptr);
      var v1 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
      wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
      return v1;
    }
    /**
     * ML-DSA-87 secret key (4896 bytes).
     * @returns {Uint8Array}
     */
    get secretKey() {
      const ret = wasm.account_secretKey(this.__wbg_ptr);
      var v1 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
      wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
      return v1;
    }
  }
  if (Symbol.dispose) Account.prototype[Symbol.dispose] = Account.prototype.free;
  exports.Account = Account;

  /**
   * Derive a Quantus account from a 32-byte seed.
   * @param {Uint8Array} seed
   * @returns {Account}
   */
  function account(seed) {
    const ptr0 = passArray8ToWasm0(seed, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.account(ptr0, len0);
    if (ret[2]) {
      throw takeFromExternrefTable0(ret[1]);
    }
    return Account.__wrap(ret[0]);
  }
  exports.account = account;

  /**
   * Derive a Quantus account from a mnemonic at the given HD indices.
   * @param {string} mnemonic
   * @param {number} account
   * @param {number} change
   * @param {number} address_index
   * @param {string | null} [passphrase]
   * @returns {Account}
   */
  function accountFromMnemonic(mnemonic, account, change, address_index, passphrase) {
    const ptr0 = passStringToWasm0(mnemonic, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    const len0 = WASM_VECTOR_LEN;
    var ptr1 = isLikeNone(passphrase)
      ? 0
      : passStringToWasm0(passphrase, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len1 = WASM_VECTOR_LEN;
    const ret = wasm.accountFromMnemonic(ptr0, len0, account, change, address_index, ptr1, len1);
    if (ret[2]) {
      throw takeFromExternrefTable0(ret[1]);
    }
    return Account.__wrap(ret[0]);
  }
  exports.accountFromMnemonic = accountFromMnemonic;

  /**
   * BIP39 mnemonic -> 64-byte seed (bridge to the seed-based API).
   * @param {string} mnemonic
   * @param {string | null} [passphrase]
   * @returns {Uint8Array}
   */
  function mnemonicToSeed(mnemonic, passphrase) {
    const ptr0 = passStringToWasm0(mnemonic, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    const len0 = WASM_VECTOR_LEN;
    var ptr1 = isLikeNone(passphrase)
      ? 0
      : passStringToWasm0(passphrase, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len1 = WASM_VECTOR_LEN;
    const ret = wasm.mnemonicToSeed(ptr0, len0, ptr1, len1);
    if (ret[3]) {
      throw takeFromExternrefTable0(ret[2]);
    }
    var v3 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
    wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
    return v3;
  }
  exports.mnemonicToSeed = mnemonicToSeed;

  /**
   * Sign an already-encoded `RuntimeCall` (e.g. polkadot.js `tx.method.toU8a()`),
   * returning the SCALE-encoded v4 extrinsic.
   * @param {Uint8Array} seed
   * @param {Uint8Array} call
   * @param {any} context
   * @returns {Uint8Array}
   */
  function signCall(seed, call, context) {
    const ptr0 = passArray8ToWasm0(seed, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passArray8ToWasm0(call, wasm.__wbindgen_malloc);
    const len1 = WASM_VECTOR_LEN;
    const ret = wasm.signCall(ptr0, len0, ptr1, len1, context);
    if (ret[3]) {
      throw takeFromExternrefTable0(ret[2]);
    }
    var v3 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
    wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
    return v3;
  }
  exports.signCall = signCall;

  /**
   * Sign an already-encoded `RuntimeCall` from a mnemonic at the given HD indices.
   * @param {string} mnemonic
   * @param {Uint8Array} call
   * @param {any} context
   * @param {number} account
   * @param {number} change
   * @param {number} address_index
   * @param {string | null} [passphrase]
   * @returns {Uint8Array}
   */
  function signCallFromMnemonic(
    mnemonic,
    call,
    context,
    account,
    change,
    address_index,
    passphrase,
  ) {
    const ptr0 = passStringToWasm0(mnemonic, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    const len0 = WASM_VECTOR_LEN;
    const ptr1 = passArray8ToWasm0(call, wasm.__wbindgen_malloc);
    const len1 = WASM_VECTOR_LEN;
    var ptr2 = isLikeNone(passphrase)
      ? 0
      : passStringToWasm0(passphrase, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len2 = WASM_VECTOR_LEN;
    const ret = wasm.signCallFromMnemonic(
      ptr0,
      len0,
      ptr1,
      len1,
      context,
      account,
      change,
      address_index,
      ptr2,
      len2,
    );
    if (ret[3]) {
      throw takeFromExternrefTable0(ret[2]);
    }
    var v4 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
    wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
    return v4;
  }
  exports.signCallFromMnemonic = signCallFromMnemonic;

  /**
   * Sign a balances/assets transfer, returning the SCALE-encoded v4 extrinsic.
   * @param {Uint8Array} seed
   * @param {any} params
   * @returns {Uint8Array}
   */
  function signTransfer(seed, params) {
    const ptr0 = passArray8ToWasm0(seed, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.signTransfer(ptr0, len0, params);
    if (ret[3]) {
      throw takeFromExternrefTable0(ret[2]);
    }
    var v2 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
    wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
    return v2;
  }
  exports.signTransfer = signTransfer;

  /**
   * Sign a transfer from a mnemonic at the given HD indices.
   * @param {string} mnemonic
   * @param {any} params
   * @param {number} account
   * @param {number} change
   * @param {number} address_index
   * @param {string | null} [passphrase]
   * @returns {Uint8Array}
   */
  function signTransferFromMnemonic(mnemonic, params, account, change, address_index, passphrase) {
    const ptr0 = passStringToWasm0(mnemonic, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    const len0 = WASM_VECTOR_LEN;
    var ptr1 = isLikeNone(passphrase)
      ? 0
      : passStringToWasm0(passphrase, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len1 = WASM_VECTOR_LEN;
    const ret = wasm.signTransferFromMnemonic(
      ptr0,
      len0,
      params,
      account,
      change,
      address_index,
      ptr1,
      len1,
    );
    if (ret[3]) {
      throw takeFromExternrefTable0(ret[2]);
    }
    var v3 = getArrayU8FromWasm0(ret[0], ret[1]).slice();
    wasm.__wbindgen_free(ret[0], ret[1] * 1, 1);
    return v3;
  }
  exports.signTransferFromMnemonic = signTransferFromMnemonic;
  function __wbg_get_imports() {
    const import0 = {
      __proto__: null,
      __wbg_Error_fdd633d4bb5dd76a: function (arg0, arg1) {
        const ret = Error(getStringFromWasm0(arg0, arg1));
        return ret;
      },
      __wbg_Number_c4bdf66bb78f7977: function (arg0) {
        const ret = Number(arg0);
        return ret;
      },
      __wbg_String_8564e559799eccda: function (arg0, arg1) {
        const ret = String(arg1);
        const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        const len1 = WASM_VECTOR_LEN;
        getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
        getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
      },
      __wbg___wbindgen_bigint_get_as_i64_d9e915702856f831: function (arg0, arg1) {
        const v = arg1;
        const ret = typeof v === 'bigint' ? v : undefined;
        getDataViewMemory0().setBigInt64(arg0 + 8 * 1, isLikeNone(ret) ? BigInt(0) : ret, true);
        getDataViewMemory0().setInt32(arg0 + 4 * 0, !isLikeNone(ret), true);
      },
      __wbg___wbindgen_boolean_get_edaed31a367ce1bd: function (arg0) {
        const v = arg0;
        const ret = typeof v === 'boolean' ? v : undefined;
        return isLikeNone(ret) ? 0xffffff : ret ? 1 : 0;
      },
      __wbg___wbindgen_debug_string_8a447059637473e2: function (arg0, arg1) {
        const ret = debugString(arg1);
        const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        const len1 = WASM_VECTOR_LEN;
        getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
        getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
      },
      __wbg___wbindgen_in_4990f46af709e33c: function (arg0, arg1) {
        const ret = arg0 in arg1;
        return ret;
      },
      __wbg___wbindgen_is_bigint_90b5ccfe67c78460: function (arg0) {
        const ret = typeof arg0 === 'bigint';
        return ret;
      },
      __wbg___wbindgen_is_function_acc5528be2b923f2: function (arg0) {
        const ret = typeof arg0 === 'function';
        return ret;
      },
      __wbg___wbindgen_is_object_0beba4a1980d3eea: function (arg0) {
        const val = arg0;
        const ret = typeof val === 'object' && val !== null;
        return ret;
      },
      __wbg___wbindgen_is_undefined_721f8decd50c87a3: function (arg0) {
        const ret = arg0 === undefined;
        return ret;
      },
      __wbg___wbindgen_jsval_eq_4e8c38722cb8ff51: function (arg0, arg1) {
        const ret = arg0 === arg1;
        return ret;
      },
      __wbg___wbindgen_jsval_loose_eq_4b9aba9e5b3c4582: function (arg0, arg1) {
        const ret = arg0 == arg1;
        return ret;
      },
      __wbg___wbindgen_number_get_1cc01dd708740256: function (arg0, arg1) {
        const obj = arg1;
        const ret = typeof obj === 'number' ? obj : undefined;
        getDataViewMemory0().setFloat64(arg0 + 8 * 1, isLikeNone(ret) ? 0 : ret, true);
        getDataViewMemory0().setInt32(arg0 + 4 * 0, !isLikeNone(ret), true);
      },
      __wbg___wbindgen_string_get_71bb4348194e31f0: function (arg0, arg1) {
        const obj = arg1;
        const ret = typeof obj === 'string' ? obj : undefined;
        var ptr1 = isLikeNone(ret)
          ? 0
          : passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        var len1 = WASM_VECTOR_LEN;
        getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
        getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
      },
      __wbg___wbindgen_throw_ea4887a5f8f9a9db: function (arg0, arg1) {
        throw new Error(getStringFromWasm0(arg0, arg1));
      },
      __wbg_call_8e98ed2f3c86c4b5: function () {
        return handleError(function (arg0, arg1) {
          const ret = arg0.call(arg1);
          return ret;
        }, arguments);
      },
      __wbg_done_b62d4a7d2286852a: function (arg0) {
        const ret = arg0.done;
        return ret;
      },
      __wbg_entries_c261c3fa1f281256: function (arg0) {
        const ret = Object.entries(arg0);
        return ret;
      },
      __wbg_get_197a3fe98f169e38: function (arg0, arg1) {
        const ret = arg0[arg1 >>> 0];
        return ret;
      },
      __wbg_get_9a29be2cb383ed9a: function () {
        return handleError(function (arg0, arg1) {
          const ret = Reflect.get(arg0, arg1);
          return ret;
        }, arguments);
      },
      __wbg_get_unchecked_54a4374c38e08460: function (arg0, arg1) {
        const ret = arg0[arg1 >>> 0];
        return ret;
      },
      __wbg_get_with_ref_key_6412cf3094599694: function (arg0, arg1) {
        const ret = arg0[arg1];
        return ret;
      },
      __wbg_instanceof_ArrayBuffer_2a7bb09fee70c2da: function (arg0) {
        let result;
        try {
          result = arg0 instanceof ArrayBuffer;
        } catch (_) {
          result = false;
        }
        const ret = result;
        return ret;
      },
      __wbg_instanceof_Map_afa18d5840c04c15: function (arg0) {
        let result;
        try {
          result = arg0 instanceof Map;
        } catch (_) {
          result = false;
        }
        const ret = result;
        return ret;
      },
      __wbg_instanceof_Uint8Array_f080092dc70f5d58: function (arg0) {
        let result;
        try {
          result = arg0 instanceof Uint8Array;
        } catch (_) {
          result = false;
        }
        const ret = result;
        return ret;
      },
      __wbg_isArray_145a34fd0a38d37b: function (arg0) {
        const ret = Array.isArray(arg0);
        return ret;
      },
      __wbg_isSafeInteger_a3389a198582f5f6: function (arg0) {
        const ret = Number.isSafeInteger(arg0);
        return ret;
      },
      __wbg_iterator_cc47ba25a2be735a: function () {
        const ret = Symbol.iterator;
        return ret;
      },
      __wbg_length_589238bdcf171f0e: function (arg0) {
        const ret = arg0.length;
        return ret;
      },
      __wbg_length_c6054974c0a6cdb9: function (arg0) {
        const ret = arg0.length;
        return ret;
      },
      __wbg_new_81880fb5002cb255: function (arg0) {
        const ret = new Uint8Array(arg0);
        return ret;
      },
      __wbg_next_0c4066e251d2eff9: function () {
        return handleError(function (arg0) {
          const ret = arg0.next();
          return ret;
        }, arguments);
      },
      __wbg_next_402fa10b59ab20c3: function (arg0) {
        const ret = arg0.next;
        return ret;
      },
      __wbg_prototypesetcall_d721637c7ca66eb8: function (arg0, arg1, arg2) {
        Uint8Array.prototype.set.call(getArrayU8FromWasm0(arg0, arg1), arg2);
      },
      __wbg_value_49f783bb59765962: function (arg0) {
        const ret = arg0.value;
        return ret;
      },
      __wbindgen_cast_0000000000000001: function (arg0) {
        // Cast intrinsic for `I64 -> Externref`.
        const ret = arg0;
        return ret;
      },
      __wbindgen_cast_0000000000000002: function (arg0, arg1) {
        // Cast intrinsic for `Ref(String) -> Externref`.
        const ret = getStringFromWasm0(arg0, arg1);
        return ret;
      },
      __wbindgen_cast_0000000000000003: function (arg0) {
        // Cast intrinsic for `U64 -> Externref`.
        const ret = BigInt.asUintN(64, arg0);
        return ret;
      },
      __wbindgen_init_externref_table: function () {
        const table = wasm.__wbindgen_externrefs;
        const offset = table.grow(4);
        table.set(0, undefined);
        table.set(offset + 0, undefined);
        table.set(offset + 1, null);
        table.set(offset + 2, true);
        table.set(offset + 3, false);
      },
    };
    return {
      __proto__: null,
      './quantus_wasm_bg.js': import0,
    };
  }

  const AccountFinalization =
    typeof FinalizationRegistry === 'undefined'
      ? { register: () => {}, unregister: () => {} }
      : new FinalizationRegistry((ptr) => wasm.__wbg_account_free(ptr, 1));

  function addToExternrefTable0(obj) {
    const idx = wasm.__externref_table_alloc();
    wasm.__wbindgen_externrefs.set(idx, obj);
    return idx;
  }

  function debugString(val) {
    // primitive types
    const type = typeof val;
    if (type == 'number' || type == 'boolean' || val == null) {
      return `${val}`;
    }
    if (type == 'string') {
      return `"${val}"`;
    }
    if (type == 'symbol') {
      const description = val.description;
      if (description == null) {
        return 'Symbol';
      } else {
        return `Symbol(${description})`;
      }
    }
    if (type == 'function') {
      const name = val.name;
      if (typeof name == 'string' && name.length > 0) {
        return `Function(${name})`;
      } else {
        return 'Function';
      }
    }
    // objects
    if (Array.isArray(val)) {
      const length = val.length;
      let debug = '[';
      if (length > 0) {
        debug += debugString(val[0]);
      }
      for (let i = 1; i < length; i++) {
        debug += ', ' + debugString(val[i]);
      }
      debug += ']';
      return debug;
    }
    // Test for built-in
    const builtInMatches = /\[object ([^\]]+)\]/.exec(toString.call(val));
    let className;
    if (builtInMatches && builtInMatches.length > 1) {
      className = builtInMatches[1];
    } else {
      // Failed to match the standard '[object ClassName]'
      return toString.call(val);
    }
    if (className == 'Object') {
      // we're a user defined class or Object
      // JSON.stringify avoids problems with cycles, and is generally much
      // easier than looping through ownProperties of `val`.
      try {
        return 'Object(' + JSON.stringify(val) + ')';
      } catch (_) {
        return 'Object';
      }
    }
    // errors
    if (val instanceof Error) {
      return `${val.name}: ${val.message}\n${val.stack}`;
    }
    // TODO we could test for more things here, like `Set`s and `Map`s.
    return className;
  }

  function getArrayU8FromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return getUint8ArrayMemory0().subarray(ptr / 1, ptr / 1 + len);
  }

  let cachedDataViewMemory0 = null;
  function getDataViewMemory0() {
    if (
      cachedDataViewMemory0 === null ||
      cachedDataViewMemory0.buffer.detached === true ||
      (cachedDataViewMemory0.buffer.detached === undefined &&
        cachedDataViewMemory0.buffer !== wasm.memory.buffer)
    ) {
      cachedDataViewMemory0 = new DataView(wasm.memory.buffer);
    }
    return cachedDataViewMemory0;
  }

  function getStringFromWasm0(ptr, len) {
    return decodeText(ptr >>> 0, len);
  }

  let cachedUint8ArrayMemory0 = null;
  function getUint8ArrayMemory0() {
    if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
      cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8ArrayMemory0;
  }

  function handleError(f, args) {
    try {
      return f.apply(this, args);
    } catch (e) {
      const idx = addToExternrefTable0(e);
      wasm.__wbindgen_exn_store(idx);
    }
  }

  function isLikeNone(x) {
    return x === undefined || x === null;
  }

  function passArray8ToWasm0(arg, malloc) {
    const ptr = malloc(arg.length * 1, 1) >>> 0;
    getUint8ArrayMemory0().set(arg, ptr / 1);
    WASM_VECTOR_LEN = arg.length;
    return ptr;
  }

  function passStringToWasm0(arg, malloc, realloc) {
    if (realloc === undefined) {
      const buf = cachedTextEncoder.encode(arg);
      const ptr = malloc(buf.length, 1) >>> 0;
      getUint8ArrayMemory0()
        .subarray(ptr, ptr + buf.length)
        .set(buf);
      WASM_VECTOR_LEN = buf.length;
      return ptr;
    }

    let len = arg.length;
    let ptr = malloc(len, 1) >>> 0;

    const mem = getUint8ArrayMemory0();

    let offset = 0;

    for (; offset < len; offset++) {
      const code = arg.charCodeAt(offset);
      if (code > 0x7f) break;
      mem[ptr + offset] = code;
    }
    if (offset !== len) {
      if (offset !== 0) {
        arg = arg.slice(offset);
      }
      ptr = realloc(ptr, len, (len = offset + arg.length * 3), 1) >>> 0;
      const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
      const ret = cachedTextEncoder.encodeInto(arg, view);

      offset += ret.written;
      ptr = realloc(ptr, len, offset, 1) >>> 0;
    }

    WASM_VECTOR_LEN = offset;
    return ptr;
  }

  function takeFromExternrefTable0(idx) {
    const value = wasm.__wbindgen_externrefs.get(idx);
    wasm.__externref_table_dealloc(idx);
    return value;
  }

  let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
  cachedTextDecoder.decode();
  function decodeText(ptr, len) {
    return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
  }

  const cachedTextEncoder = new TextEncoder();

  if (!('encodeInto' in cachedTextEncoder)) {
    cachedTextEncoder.encodeInto = function (arg, view) {
      const buf = cachedTextEncoder.encode(arg);
      view.set(buf);
      return {
        read: arg.length,
        written: buf.length,
      };
    };
  }

  let WASM_VECTOR_LEN = 0;

  const resolved = await source;
  const imports = __wbg_get_imports();
  let instance;
  if (typeof Response !== 'undefined' && resolved instanceof Response) {
    if (!resolved.ok)
      throw new Error('Failed to fetch quantus_wasm_bg.wasm: HTTP ' + resolved.status);
    // instantiateStreaming needs the application/wasm MIME type; fall back to a buffer otherwise.
    const fallback = resolved.clone();
    try {
      ({ instance } = await WebAssembly.instantiateStreaming(resolved, imports));
    } catch {
      ({ instance } = await WebAssembly.instantiate(await fallback.arrayBuffer(), imports));
    }
  } else {
    ({ instance } = await WebAssembly.instantiate(resolved, imports));
  }
  wasm = instance.exports;
  wasm.__wbindgen_start();
  return exports;
}
